name: test
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  print-config:
    runs-on: ubuntu-latest

    steps:
      - name: Print the YAML file content
        run: cat config.yaml
